server:
  port: 8001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 80000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  routes:
    auth:
      path: /api/auth/**
      serviceId: amz-microservice-auth
      sensitiveHeaders:
    product:
      path: /api/product/**
      serviceId: amz-microservice-product
      sensitiveHeaders:
    account:
      path: /api/account/**
      serviceid: amz-microservice-account
      sensitiveHeaders:
  host:
    socket-timeout-millis: 30000


---

spring:
  profiles: dev

eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    lease-expiration-duration-in-seconds: 5
  client:
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://52.58.55.103:8000/eureka/
